# Generated by Django 4.2.7 on 2023-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittingwala', '0002_fituser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fituser',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
