# Generated by Django 4.2.7 on 2023-11-25 13:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittingwala', '0003_alter_fituser_verification_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fituser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='fituser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fituser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
